[package]
name = "synacor_challenge"
version = "0.0.1"
authors = ["boarder2"]
[dependencies]
time = "*"
byteorder = "*"
clap = "2.*"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.81"